- block:
    - name: Validacion del tamaño VG Java 
      become: true
      shell: |
        vgfree=$(vgs | grep -i VGAPPS | tr -s ' ' ',' | cut -d, -f8 | tr -d '<gG' | cut -d. -f1)
        if [ $vgfree -ge 6 ]; then
        echo "OK,$vgfree"
        elif [ $vgfree -ge 5 ]; then
        echo "KO,$vgfree"
        elif [ $vgfree -ge 4 ]; then
        echo "KO,$vgfree"
        fi
      register: vgszjav

    - name: Validacion del tamaño LV Java 
      become: true
      shell: |
        freelv=$(df 2>/dev/null -h | grep "java_atm" | tr -s ' ' ',' | cut -d, -f5 | tr -d '%')
        if [ 50 -ge $freelv ] || [ 65 -ge $freelv ]; then
          echo "OK,$freelv"
        elif [ 70 -ge $freelv ] || [ 85 -ge $freelv ]; then
          echo "KO,$freelv"
        elif [ 95 -ge $freelv ]; then
          echo "KO,$freelv"
        fi
      register: lvszjav

    - name: Extender el volumen logico
      become: true
      lvol:
        vg: VGAPPS
        lv: LVJAVACTM
        size: 5.1G
        resizefs: true
        force: true
      when: vgszjav.stdout.split(',')[0] == "OK" and lvszjav.stdout.split(',')[0] != "OK"