---
- name: Almacenar evidencias previas y posteriores al IPL de servicios, discos y salud del OS Windows
  block:
    - name: Envio de evidencias por CRQ, INC o REQ
      win_shell: |
        $sendMailMessageSplat = @{
        From = '{{ mailfrom }}'
        To = '{{ mailto }}'
        Subject = "{{ mailsub }}"
        Body = "Hola Mundo!"
        SmtpServer = '150.100.207.52'
        Attachments = $archivos
        }
        Send-MailMessage @sendMailMessageSplat
  delegate_to: wvmbao01.bvm.bluecare.kyndryl.net
