---
- name: Cierre de vulneravilidades NetBackup
  block:
    - name: Validar unidad
      win_shell: Get-PSDrive -PSProvider FileSystem | Select-Object -ExpandProperty Name
      register: unidades_logicas


#    - name: Crear directorio {{ disco }}
#      win_file:
#        path: "{{ disco }}TEMP"
#        state: directory
