- block:
    - name: Gather the rpm package facts
      package_facts:
        manager: auto

    # - name: Print the rpm package facts
    #   debug:
    #     var: ansible_facts.packages

    # - name: Check whether a package called tar is installed
    #   debug:
    #     msg: "{{ ansible_facts.packages['tar'] | length }} versions of tar are installed!"
    #   when: "'tar' in ansible_facts.packages"

    - set_fact:
        tar: "{{ ansible_facts.tar[0].name }}-{{ ansible_facts.tar[0].version }}"

    - name: Resultado de la validacion VG VGAPPS
      assert:
        that:
          - "'tar' in ansible_facts.packages"
        fail_msg: "El rpm {{ tar | default('tar_x86_64') }} no esta instalado"
        success_msg: "La rpm {{ tar }}, esta instalado"