---
- name: Validar usuario Qualys env. produccion
  become: true
  shell: grep -qw zmqalysp /etc/passwd >/dev/null && echo "Usuario zmqalysp existe en el servidor" || echo "Sin Usuario Desarrollo Qualys"
  register: checkuidp
  when: hostvars[inventory_hostname].entorno == "PR"

- name: Resultado de la validacion de usuario Qualys
  assert:
    that:
      - "'zmqalysp' in checkuidp.stdout"
    fail_msg: "{{ checkuidp.stdout }}"
    success_msg: "{{ checkuidp.stdout }}"
  when: hostvars[inventory_hostname].entorno == "PR"

- name: Validar usuario Qualys env. desarrollo
  become: true
  shell: grep -qw zmqalysd /etc/passwd >/dev/null && echo "Usuario zmqalysd existe en el servidor" || echo "Sin Usuario Desarrollo Qualys"
  register: checkuidd
  when: hostvars[inventory_hostname].entorno == "EP"

- name: Resultado de la validacion de usuario Qualys
  assert:
    that:
      - "'zmqalysd' in checkuidd.stdout"
    fail_msg: "{{ checkuidd.stdout }}"
    success_msg: "{{ checkuidd.stdout }}"
  when: hostvars[inventory_hostname].entorno == "EP"

- name: Validar espacio en el VGPROGPROD
  become: true
  shell: |
    VFree=$(vgs --units g --noheadings -o vg_free {{ vgname }} | tr -d ' ')
    VFree_GB=$(echo $VFree | tr -d 'gG')
    if (( $(echo "$VFree_GB < {{ vgsize }}" | bc -l) )); then
        echo KO
    else
        echo 
    fi

- name: Validar espacio en el VGPROGPROD
  become: true
  shell: 
