---
- name: Cierre de vulneravilidades NetBackup
  block:
    - name: Validar si la unidad V:\ existe
      win_shell: Get-PSDrive -PSProvider FileSystem | Select-Object -ExpandProperty Name
      register: unidades

    - name: Filtrar IP de Robotica
      set_fact:
        unidad_asb: "{{ unidades.stdout_lines | select('match', '^D|^V') | list }}"

    - name: Mostrar unidad seleccionada
      debug:
        msg: "La unidad seleccionada para almacenar logs es: {{ unidad_asb | replace('[', '' ) | replace(']', '' ) | trim | regex_replace(\"'\", '') }}:\"

#    - name: Crear directorio
#      win_file:
#        path: {{ unidad_asb  | replace('[', '' ) | replace(']', '' ) | trim | regex_replace(\"'\", '') }}:\TEMP
#        state: directory
