---
- name: Cierre de vulneravilidades NetBackup
  block:
    - name: Validar si las unidad D:\ y/o V:\ existen
      win_shell: Get-PSDrive -PSProvider FileSystem | Select-Object -ExpandProperty Name
      register: letradisco

    - name: Filtrar unidades
      set_fact:
        unidads: "{{ letradisco.stdout_lines | select('match', '^D|^V') | list }}"
        unudad_asd: "{{ unidades | replace('[', '' ) | replace(']', '' ) | trim | regex_replace(\"'\", '') }}"

    - name: Mostrar unidad seleccionada
      debug:
#        msg: "La unidad seleccionada para almacenar logs es: {{ unidad_asb | replace('[', '' ) | replace(']', '' ) | trim | regex_replace(\"'\", '') }}"
        msg: "La unidad seleccionada para almacenar logs es: {{ unidad_asb }}"

#    - name: Crear directorio
#      win_file:
#        path: {{ unidad_asb  | replace('[', '' ) | replace(']', '' ) | trim | regex_replace(\"'\", '') }}:\TEMP
#        state: directory
