---
- name: Tareas por bloques - Validacion formato CRQ o ICR
  block:
    - name: Validando Formato de Cambio o Incidente
      assert:
        that:
          - idcrqincreq | string | regex_search('(CRQ|INC|REQ)[0-9]{12}')
        fail_msg: "El CRQ, INC o REQ no cumplen con la condiciones del formato"
        success_msg: "El CRQ, INC o REQ cumplen con las condiciones del formato"
      run_once: true
      delegate_to: localhost

- name: Test Transferir - Descargar
  block:
    - name: Transferir archivo plano
      become: true
      fetch:
        src: /var/opt/ansible/CRQ000101107715_mzreposmq1_150.100.97.5_foto_sso_pp_aps_previa.txt
        dest: /tmp/
        flat: yes

    - name: Validar archivos split en el localhost
      local_action:
        module: shell
        args: "ls -lrt /tmp