- block:
    - set_fact:
        nombre_servidor: "{{ inventory_hostname.split('.')[0] }}"
        direccion_ip: "{{ hostvars[inventory_hostname].ipaddress }}"

    - name: Forzar a un FALLO
      assert:
        that:
          - "'OK' in evaluacion"
        fail_msg: "{{ nombre_servidor }},{{ direccion_ip }},FALLA"
        success_msg: "{{ nombre_servidor }},{{ direccion_ip }},CORRECTO"
      when: "'KO' in evaluacion"

    - name: Reporte - Hostname, IPs, Uptime posterior IPL
      debug: 
        msg: "{{ nombre_servidor }}-{{ direccion_ip }}"

    - name: Registrar Hostname e IP
      shell: "echo {{ nombre_servidor }}-{{ direccion_ip }} > status_equipos.txt"
      args:
        chdir: /tmp

    - name: Obtener salida Hostname e IP
      shell: cat status_equipos.txt
      args:
        chdir: /tmp
      register: salidahostip
    
    - set_fact:
        cpremotehostip: "{{ salidahostip.stdout_lines }}" 

- block:
    - lineinfile:
        path: /tmp/concentrado1.txt
        line: "{{ cpremotehostip | join('\n') }}"
        create: true
  delegate_to: lvbtst01.bvm.bluecare.kyndryl.net