- block:
    - set_fact:
        nombre_servidor: "{{ inventory_hostname.split('.')[0] }}"
        direccion_ip: "{{ hostvars[inventory_hostname].ipaddress }}"


    - name: Reporte - Hostname, IPs, Uptime posterior IPL
      debug: 
        msg: "{{ nombre_servidor }}-{{ direccion_ip }}"

    - name: Registrar Hostname e IP
      shell: "echo {{ nombre_servidor }}-{{ direccion_ip }} > status_equipos.txt"
      args:
        chdir: /tmp

    - name: Obtener salida Hostname e IP
      shell: cat status_equipos.txt
      args:
        chdir: /tmp
      register: salidahostip
    
    - set_fact:
        cpremotehostip: "{{ salidahostip.stdout_lines }}" 

- block:
    - copy:
        content: "{{ cpremotehostip | join('\n') }}"
        dest: /tmp/concentrado.txt
  delegate_to: lvbtst01.bvm.bluecare.kyndryl.net