---
- name: Cierre de vulneravilidades NetBackup
  block:
    - name: Validar si las unidad D:\ y/o V:\ existen
      win_shell: Get-PSDrive -PSProvider FileSystem | Select-Object -ExpandProperty Name
      register: letradisco

    - name: Filtrar unidades
      set_fact:
        unidades: "{{ letradisco.stdout_lines | select('match', '^D|^V') | list }}"

    - name: Mostrar unidad seleccionada
      debug:
        msg: "{{ unidades | replace('[', '' ) | replace(']', '' ) | trim | regex_replace(\"'\", '') }}"

    - name: Filtrar unidades1
      set_fact:
        unudad_asb: "{{ unidades | replace('[', '' ) | replace(']', '' ) | trim | regex_replace(\"'\", '') }}"

    - name: Listar contenido de la unidad
      win_shell: dir "{{ unidad_asb }}"

#    - name: Crear directorio
#      win_file:
#        path: {{ unidad_asb  | replace('[', '' ) | replace(']', '' ) | trim | regex_replace(\"'\", '') }}:\TEMP
#        state: directory
