- block:
    - name: Recopilar datos de paquete rpm
      package_facts:
        manager: auto

    # - name: Print the rpm package facts
    #   debug:
    #     var: ansible_facts.packages

    # - name: Check whether a package called tar is installed
    #   debug:
    #     msg: "{{ ansible_facts.packages['tar'] | length }} versions of tar are installed!"
    #   when: "'tar' in ansible_facts.packages"

    - set_fact:
        tar_rpm: "{{ ansible_facts.packages.tar[0].name }}-v{{ ansible_facts.packages.tar[0].version }}"

    - name: Resultado de recopilar datos de paquete rpm 
      assert:
        that:
          - "'tar' in ansible_facts.packages"
        fail_msg: "El rpm {{ tar_rpm | default('tar_x86_64') }} no esta instalado"
        success_msg: "La rpm {{ tar_rpm }}, esta instalado"