---
- name: Ejecutar shell script - reporte XML Control-M mallas
  block:
    - name: Ejecutar script CTM obtener_mallas_ADA.sh
      shell: |
        echo -e "\n\nINICIANDO PROCESO\n\n\nCREANDO ARCHIVO ARG PARA USAR EN SIGUIENTE PASO\n\n\nEXPORTANDO TABLAS\n\n\nInfo: Returned buffer contains 3529 folders\nInfo: Export completed successfully with 3529 Folders, 0 Smart Folders, 0 Sub Folders, and 107496 Jobs, exported to /Ctrlmemp/portal/archivos/export_CCR_ADA.xml\n\n0\n\nLIMPIANDO  ARCHIVOS TEMPORALES\n\n\nPROCESO TERMINADO"
      register: ctmscript

    - name: Limpiar mensaje salida reporte XML Control-M mallas
      set_fact:
        ctnmsg: "{{ ctmscript.stdout_lines }}"

    - name: Copiar archivo XML de mallas Control-M a directorio temporal
      become: true
      copy:
        src: /Ctrlmemp/portal/archivos/export_CCR_ADA.xml
        dest: /tmp
        remote_src: true

    - name: Comprimir archivo XML de mallas Control-M a directorio temporal
      become: true
      archive:
        path: /tmp/export_CCR_ADA.xml
        dest: /tmp/export_CCR_ADA.zip
        format: zip
        owner: ccrbao
        group: grpcrbao
        mode: '0775'
 
- name: Transferencia archivo XML de mallas a
  block:
    - name: Transferir archivo XML de mallas Control-M a equipo remoto
      become: true
      become_user: ccrbao
      become_method: su
      become_exe: sudo su -
      shell: |
        eval $(ssh-agent -s)
        echo "{{ mi_passphrase }}" | ssh-add /home/ccrbao/.ssh/id_rsa
        scp -o StrictHostKeyChecking=no ccrbao@{{ hostvars[inventory_hostname].ipaddress }}:/tmp/export_CCR_ADA.zip /tmp
      args:
        executable: /bin/bash
      no_log: false        

    - name: Validar archivo XML de mallas Control-M en equipo remoto
      become: true
      stat:
        path: /tmp/export_CCR_ADA.zip
      register: valarch

    - name: Envir por correo del archivo XML de mallas Control-M
      mail:
        host: "{{ smtp }}"
        port: "{{ smtpport }}"
        from: "{{ mailfrom }}"
        to: "{{ mailto }}"
        subject: "{{ mailsub }}"
        body: "{{ ctnmsg | join('\n') }}"
        attach: /tmp/export_CCR_ADA.zip
      register: valmail
      run_once: true
      when: valarch.stat.exists == true

    - name: Validar archivo XML de mallas Control-M en equipo remoto
      become: true
      file:
        path: /tmp/export_CCR_ADA.xml
        state: absent
      run_once: true
  delegate_to: asitsmaop0.bvm.bluecare.kyndryl.net

- name: Borrar archivo XML de mallas en equipo remoto
  block:
    - name: Validar archivo XML de mallas Control-M en equipo remoto
      become: true
      file:
        path: /tmp/{{ item }}
        state: absent
      loop:
        - export_CCR_ADA.xml
        - export_CCR_ADA.zip
