---
- name: Cierre de vulneravilidades NetBackup
  block:
    - name: Validar si las unidad D:\ y/o V:\ existen
      win_shell: Get-PSDrive -PSProvider FileSystem | Select-Object -ExpandProperty Name
      register: unidades

    - name: Filtrar unidades
      set_fact:
        unidads: "{{ unidades.stdout_lines | select('match', '^D|^V') | list }}"
        unudad_d: "{{ unidad_asb | select('match', '^D') | list | replace('[', '' ) | replace(']', '' ) | trim | regex_replace(\"'\", '') }}"
        unudad_v: "{{ unidad_asb | select('match', '^V') | list | replace('[', '' ) | replace(']', '' ) | trim | regex_replace(\"'\", '') }}"

    - name: Mostrar unidad seleccionada
      debug:
#        msg: "La unidad seleccionada para almacenar logs es: {{ unidad_asb | replace('[', '' ) | replace(']', '' ) | trim | regex_replace(\"'\", '') }}"
        msg: "La unidad seleccionada para almacenar logs es: {{ unidad_asb }}"

#    - name: Crear directorio
#      win_file:
#        path: {{ unidad_asb  | replace('[', '' ) | replace(']', '' ) | trim | regex_replace(\"'\", '') }}:\TEMP
#        state: directory
