---
- name: Cierre de vulneravilidades NetBackup
  block:
    - name: Validar si la unidad V:\ existe
      win_shell: |
        $driveRoot = Get-PSDrive -PSProvider FileSystem | Where-Object { $_.Root -eq 'V:\' } | Select-Object -ExpandProperty Root -ErrorAction SilentlyContinue
        if ($driveRoot) {
          Write-Host "V:\"
        } else {
          Write-Host "D:\"
        }
      register: unidad_asb


    - name: Crear directorio {{ unidad_asb.stdout }}
      win_file:
        path: "{{ unidad_asb.stdout }}TEMP"
        state: directory
