---
- name: Pruebas de Unidades Windows
  block:
    - name: Validar si las unidad D:\ y/o V:\ existen
      win_shell: Get-PSDrive -PSProvider FileSystem | Select-Object -ExpandProperty Root
      register: windrives

    - name: Filtrar unidades
      set_fact:
        windriv: "{{ windrives.stdout_lines | select('match', '^D|^V') | list | replace('[', '' ) | replace(']', '' ) | replace(' ', '') | trim | regex_replace(\"'\", '') }}"

    - name: Mostrar unidades
      debug:
        msg: "{{ windriv.split(',')[1] }}"

    # - name: Crear directorio
    #   win_file:
    #     path: "{{ windriv }}TEMP"
    #     state: directory

    # - name: Listar contenido de la unidad
    #   win_shell: dir "{{ windriv }}"