---
- name: Cierre de vulneravilidades NetBackup
  block:
    - name: Validar si las unidad D:\ y/o V:\ existen
      win_shell: Get-PSDrive -PSProvider FileSystem | Select-Object -ExpandProperty Root
      register: letradisco

    - name: Filtrar unidades
      set_fact:
        unidades: "{{ letradisco.stdout_lines | select('match', '^D|^V') | list | replace('[', '' ) | replace(']', '' ) | trim | regex_replace(\"'\", '') }}"

    - name: Mostrar unidades
      debug:
        msg: "{{ unidades | replace('[', '' ) | replace(']', '' ) | trim | regex_replace(\"'\", '') }}"

    - name: Filtrar unidades1
      set_fact:
        unudad_asb: "{{ unidades | replace('[', '' ) | replace(']', '' ) | trim | regex_replace(\"'\", '') | select('match', '^D|^V') | list }}"

    - name: Mostrar unidades2
      debug:
        msg: "{{ unudad_asb }}"

    - name: Listar contenido de la unidad
      win_shell: dir "{{ unidades }}"

#    - name: Crear directorio
#      win_file:
#        path: {{ unidad_asb  | replace('[', '' ) | replace(']', '' ) | trim | regex_replace(\"'\", '') }}:\TEMP
#        state: directory
