---
- name: Bloques Nun.1
  shell: echo "VGAPPS,KO"
  register: info1

- name: Crear echos dinamicos
  set_fact:
    valor: "{{ info1.stdout.split(',')[1] }}"

- name: Validando Formato de Cambio o Incidente
  assert:
    that:
      - "'OK' in valor"
    fail_msg: 
      - "No, no es OK"
      - "Tomar accion de la siguiente forma"
      - "URL:  http://ansible.com"
    success_msg: "Si, so es OK"