---
- block:
    - name: Validar script Control-M - obtener_mallas_ADA.sh
      become: true
      stat:
        path: /Ctrlmemp/portal/scripts/obtener_mallas_ADA.sh
      register: valscript

    - name: Enviar correo de notificacion de alertamiento en caso de no existir script
      mail:
        host: "{{ smtp }}"
        port: "{{ smtpport }}"
        from: "{{ mailfrom }}"
        to: "{{ mailtoA1 }}"
        subject: "{{ mailsubA1 }}"
        subtype: html
        body: "{{ mailbodyA1 }}"
      run_once: true
      when: not valscript.stat.exists
      delegate_to: asitsmaop2.bvm.bluecare.kyndryl.net

    - name: Resultado de validar archivo XML de mallas Control-M en equipo remoto
      assert:
        that:
          - valscript.stat.exists
        fail_msg: "El script Control-M - obtener_mallas_ADA.sh no existe o tiene otro nombre, se envio notificacion por correo"
        success_msg: "El script Control-M - obtener_mallas_ADA.sh existe, se proceder con su ejecucion"

- block:
#     - name: Ejecutar script Control-M - obtener_mallas_ADA.sh
#       become: true
#       become_user: ctrlmem
#       become_method: su
#       become_exe: sudo su -
#       shell: ./obtener_mallas_ADA.sh
#       args:
#         chdir: /Ctrlmemp/portal/scripts
#       register: ctmscript_async
#       async: 3600
#       poll: 0

#     - name: Esperar a que termine el script Control-M (hasta el timeout)
#       become: true
#       become_user: ctrlmem
#       become_method: su
#       become_exe: sudo su -
#       async_status:
#         jid: "{{ ctmscript_async.ansible_job_id }}"
#       register: async_result
#       until: async_result.finished or async_result.failed
#       retries: 3600 
#       delay: 60

    - name: Utilizar echo para ambientar variables script Control-M
      set_fact:
        # ctnmsg: "{{ async_result.stdout_lines }}"
        current_day: "{{ lookup('pipe', 'date +%d%m%y' ) }}"

    - name: Renombrar archivo fechado XML de mallas Control-M
      become: true
      copy:
        src: /Ctrlmemp/portal/archivos/export_CCR_ADA.xml
        dest: "/Ctrlmemp/portal/archivos/export_CCR_ADA_{{ current_day }}.xml"
        owner: ctrlmem
        group: grpctrlm
        mode: '0755'
        remote_src: true

    - name: Comprimir archivo fechado XML de mallas Control-M
      become: true
      archive:
        path: "/Ctrlmemp/portal/archivos/export_CCR_ADA_{{ current_day }}.xml"
        dest: /Ctrlmemp/portal/archivos/export_CCR_ADA.zip
        format: zip
        owner: ctrlmem
        group: grpctrlm
        mode: '0755'

    - name: Carga archivo fechado XML de mallas Control-M a Nodo de Control
      become: true
      fetch:
        src: /Ctrlmemp/portal/archivos/export_CCR_ADA.zip
        dest: /tmp/
        flat: true
      run_once: true

    - name: Remover archivo fechado XML de mallas Control-M
      become: true
      file:
        path: "/Ctrlmemp/portal/archivos/export_CCR_ADA_{{ current_day }}.xml"
        state: absent

- block:
    - name: Descarga archivo XML de mallas Control-M al Nodo Administrado
      become: true
      copy:
        src: /tmp/export_CCR_ADA.zip
        dest: /Ctrlmccrp/
        owner: ctrlmmx
        group: grpctrlm
        remote_src: false

    - name: Validar archivo zip de mallas Control-M
      become: true
      stat:
        path: /Ctrlmccrp/export_CCR_ADA.zip
      register: valarch

    - name: Enviar correo de notificacion de alertamiento en caso de no existir archivo zip de mallas Control-M
      mail:
        host: "{{ smtp }}"
        port: "{{ smtpport }}"
        from: "{{ mailfrom }}"
        to: "{{ mailtoA2 }}"
        subject: "{{ mailsubA2 }}"
        subtype: html
        body: "{{ mailbodyA2 }}"
      run_once: true
      when: not valarch.stat.exists
      delegate_to: asitsmaop2.bvm.bluecare.kyndryl.net

    - name: Resultado de validar archivo XML de mallas Control-M en equipo remoto
      assert:
        that:
          - valarch.stat.exists
        fail_msg: "No existe archivo export_CCR_ADA.zip de respaldo de mallas Control-M"
        success_msg: "Existe archivo export_CCR_ADA.zip de respaldo de mallas Control-M"

    - name: Descomprimir archivo gz XML de mallas Control-M a directorio temporal
      become: true
      unarchive:
        src: /Ctrlmccrp/export_CCR_ADA.zip
        dest: /Ctrlmccrp/
        owner: ctrlmmx
        group: grpctrlm
        remote_src: true

    - name: Remover archivo zip de mallas Control-M
      become: true
      file:
        path: /Ctrlmccrp/export_CCR_ADA.zip
        state: absent

    - name: Buscar archivos XML de mallas Control-M con más de 7 días de antigüedad
      find:
        paths: /Ctrlmccrp
        patterns: "export_CCR_ADA*.xml"
        age: 7d
        recurse: no
      register: archxmlrem

    - name: Borrar archivos XML de mallas Control-M con más de 7 días de antigüedad
      become: true
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ archxmlrem.files }}"
  delegate_to: vbldtst00.bvm.bluecare.kyndryl.net


#     - name: Envir por correo del archivo XML de mallas Control-M
#       mail:
#         host: "{{ smtp }}"
#         port: "{{ smtpport }}"
#         from: "{{ mailfrom }}"
#         to: "{{ mailto }}"
#         subject: "{{ mailsub }}"
#         body: "Por este medio se anexa el archivo export_CCR_ADA.zip y la salida de la ejecucion del script obtener_mallas_ADA.sh {{ ctnmsg | join('\n') }}"
#         attach: /tmp/export_CCR_ADA.zip
#       register: valmail
#       run_once: true
#       when: valarch.stat.exists == true

#     - name: Validar archivo XML de mallas Control-M en equipo remoto
#       become: true
#       file:
#         path: /tmp/export_CCR_ADA.zip
#         state: absent
#       run_once: true

#     - name: Borrar archivo XML de mallas Control-M en equipo remoto
#       become: true
#       file:
#         path: /tmp/export_CCR_ADA.zip
#         state: absent
#       run_once: true
#   delegate_to: asitsmaop0.bvm.bluecare.kyndryl.net

# - name: Borrar archivo XML de mallas en equipo remoto
#   block:
#     - name: Borrar archivo XML de mallas Control-M en equipo remoto
#       become: true
#       file:
#         path: /tmp/{{ item }}
#         state: absent
#       loop:
#         - export_CCR_ADA.xml
#         - export_CCR_ADA.zip
