---
- name: Buscar y eliminar archivo en C:/Temp
  tasks:
    - name: Validar si existe el archivo UCDAgent.ps1
      win_shell: |
        $FicheroUDC = "C:\Temp\UCDAgent.ps1"
        $ValidPath = Test-Path $FicheroUDC
        $ServerName = hostname
        If ($ValidPath -eq $True) {Write-Host "El fichero UDC Existe en el equipo $ServerName es borrado"} Else {Write-Host "El fichero UDC No Existe en el equipo $ServerName "}
      register: fichero

    - name: Eliminar archivo si existe
      win_file:
        path: C:\\Temp\\UCDAgent.ps1
        state: absent
      when: "'UDC Existe' in fichero.stdout"

    - name: Eliminar archivo si existe
      debug:
        msg: 