---
- name: Cierre de vulneravilidades NetBackup
  block:
    - name: Validar si las unidad D:\ y/o V:\ existen
      win_shell: Get-PSDrive -PSProvider FileSystem | Select-Object -ExpandProperty Root
      register: letradisco

    - name: Filtrar unidades
      set_fact:
        unidad_ansible: "{{ letradisco.stdout_lines | select('match', '^D|^V') | list | replace('[', '' ) | replace(']', '' ) | trim | regex_replace(\"'\", '') }}"

    - name: Mostrar unidades
      debug:
        msg: "{{ unidad_ansible }}"

    - name: Crear directorio
      win_file:
        path: "{{ unidad_ansible }}TEMP"
        state: directory

    - name: Listar contenido de la unidad
      win_shell: dir "{{ unidad_ansible }}"