---
- name: Tareas por bloques - Validacion formato CRQ o ICR
  block:
    - name: Validando Formato de Cambio o Incidente
      assert:
        that:
          - idcrqincreq | string | regex_search('(CRQ|INC|REQ)[0-9]{12}')
        fail_msg: "El CRQ, INC o REQ no cumplen con la condiciones del formato"
        success_msg: "El CRQ, INC o REQ cumplen con las condiciones del formato"
      run_once: true
      delegate_to: localhost

#- name: Ejecucion de IPL Total con evidencias previas, posteriores, reinicio y tiempo activo de OS Linux
#  block:
#    - name: Incluye la tarea de obtner fotos previa antes del IPL
#      include_tasks: Foto_previa_IPL.yml

- name: altas de Programas Producto antes de IPL de OS Linux
  block:
    - name: alta de Programas Producto
      shell: if [ -f {{ gdmlcfsasb }}patrol.asb ]; then echo alta; fi
      register: alta_patrol

    - include_tasks: roles/role_quick_test/tasks/altas_ppaps/alta_patrol.yml
      when: alta_patrol.stdout == "alta"

    - shell: if [ -f {{ gdmlcfsasb }}capacity.asb ]; then echo alta; fi
      register: alta_capacity

    - include_tasks: roles/role_quick_test/tasks/altas_ppaps/alta_capacity.yml
      when: alta_capacity.stdout == "alta"

    - shell: if [ -f {{ gdmlcfsasb }}ctm.asb ]; then echo alta; fi
      register: alta_controlm

    - include_tasks: roles/role_quick_test/tasks/altas_ppaps/alta_controlm.yml
      when: alta_controlm.stdout == "alta"

    - shell: if [ -f {{ gdmlcfsasb }}dim.asb ]; then echo alta; fi
      register: alta_dimensions

    - include_tasks: roles/role_quick_test/tasks/altas_ppaps/alta_dimensions.yml
      when: alta_dimensions.stdout == "alta"

    - shell: if [ -f {{ gdmlcfsasb }}cd.asb ]; then echo alta; fi
      register: alta_connectdirect

    - include_tasks: roles/role_quick_test/tasks/altas_ppaps/alta_connectdirect.yml
      when: alta_connectdirect.stdout == "alta"

#    - shell: if [ -f {{ gdmlcfsasb }}s1.asb ]; then echo alta; fi
#      register: alta_s1

#    - include_tasks: roles/role_quick_test/tasks/altas_ppaps/alta_sentinelone.yml
#      when: alta_s1.stdout == "alta"

- name: altas de Aplicaciones antes de IPL de OS Linux
  block:
    - name: alta Aplicaciones
      shell: if [ -f {{ gdmlcfsasb }}httpserver80s.asb ]; then echo alta; fi
      register: alta_http80s

    - shell: |
        for https $(cat {{ gdmlcfsasb }}httpserver80s.asb)
        do
          $i stop
        done
      when: alta_http80s.stdout == "alta"

    - shell: if [ -f {{ gdmlcfsasb }}httpserver80d.asb ]; then echo alta; fi
      register: alta_http80d

    - shell: |
        for https $(cat {{ gdmlcfsasb }}httpserver80d.asb)
        do
          $i stop
        done
      when: alta_http80d.stdout == "alta"

    - shell: if [ -f {{ gdmlcfsasb }}httpserver85d.asb ]; then echo alta; fi
      register: alta_http85s

    - shell: |
        for https $(cat {{ gdmlcfsasb }}httpserver85s.asb)
        do
          $i stop
        done
      when: alta_http85s.stdout == "alta"

    - shell: if [ -f {{ gdmlcfsasb }}httpserver85d.asb ]; then echo alta; fi
      register: alta_http85d

    - shell: |
        for https $(cat {{ gdmlcfsasb }}httpserver85d.asb)
        do
          $i stop
        done
      when: alta_http85d.stdout == "alta"

    - shell: if [ -f {{ gdmlcfsasb }}httpserver90d.asb ]; then echo alta; fi
      register: alta_http90s

    - shell: |
        for https $(cat {{ gdmlcfsasb }}httpserver90s.asb)
        do
          $i stop
        done
      when: alta_http90s.stdout == "alta"

    - shell: if [ -f {{ gdmlcfsasb }}httpserver90d.asb ]; then echo alta; fi
      register: alta_http90d

    - shell: |
        for https $(cat {{ gdmlcfsasb }}httpserver90d.asb)
        do
          $i stop
        done
      when: alta_http90d.stdout == "alta"

    - shell: if [ -f {{ gdmlcfsasb }}websphere80.asb ]; then echo "/WebSphere80/"; fi
      register: wasversion

    - name: Ejecutar script alta Clusters WebSphere80
      become: yes
      shell: |
        export PATH=$PATH:/sbin:/usr/sbin
        CLUSTER_R=$(ls -1R {{ wasversion.stdout }} | grep clusters:$ | grep "App\w*/pro\w*/Dmg\w*/con\w*/cel\w*/$(uname -n)" | tr ":" "/")
        CLUSTER_I=$(ls -1 $CLUSTER_R)
        for cluwasi in $CLUSTER_I
          do
          ./wsadmin.sh -lang jython -f ./alta_Cluster.py $cluwasi
          done
      args:
        chdir: "{{ wasversion.stdout }}AppServer/profiles/Dmgr01/bin/"
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ ansible_env.PATH }}"
      when: "'WebSphere80' in wasversion.stdout"


    - shell: if [ -f {{ gdmlcfsasb }}websphere85.asb ]; then echo "/WebSphere85/"; fi
      register: wasversion

    - name: Ejecutar script alta Clusters WebSphere85
      become: yes
      become_user: was60
      become_method: su
      become_exe: sudo su -
      shell: |
        export PATH=$PATH:/sbin:/usr/sbin
        CLUSTER_R=$(ls -1R {{ wasversion.stdout }} | grep clusters:$ | grep "App\w*/pro\w*/Dmg\w*/con\w*/cel\w*/$(uname -n)" | tr ":" "/")
        CLUSTER_I=$(ls -1 $CLUSTER_R)
        for cluwasi in $CLUSTER_I
          do
          ./wsadmin.sh -lang jython -f ./alta_Cluster.py $cluwasi
          done
      args:
        chdir: "{{ wasversion.stdout }}AppServer/profiles/Dmgr01/bin/"
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ ansible_env.PATH }}"
      when: "'WebSphere85' in wasversion.stdout"

    - shell: if [ -f {{ gdmlcfsasb }}websphere90.asb ]; then echo "/WebSphere90/"; fi
      register: wasversion

    - name: Ejecutar script alta Clusters WebSphere90
      become: yes
      become_user: was60
      become_method: su
      become_exe: sudo su -
      shell: |
        export PATH=$PATH:/sbin:/usr/sbin
        CLUSTER_R=$(ls -1R {{ wasversion.stdout }} | grep clusters:$ | grep "App\w*/pro\w*/Dmg\w*/con\w*/cel\w*/$(uname -n)" | tr ":" "/")
        CLUSTER_I=$(ls -1 $CLUSTER_R)
        for cluwasi in $CLUSTER_I
          do
          ./wsadmin.sh -lang jython -f ./alta_Cluster.py $cluwasi
          done
      args:
        chdir: "{{ wasversion.stdout }}AppServer/profiles/Dmgr01/bin/"
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ ansible_env.PATH }}"
      when: "'WebSphere90' in wasversion.stdout"
#----
    - shell: if [ -f {{ gdmlcfsasb }}mqm.asb ]; then echo alta; fi
      register: alta_mqm

    - name: alta canales MQ
      become: yes
      become_user: mqm
      become_method: su
      become_exe: sudo su -
      shell: |
        for i in $(cat {{ gdmlcfsasb }}mqm.asb)
        do
        $(cat {{ gdmlcfsasb }}mqma.asb) $i
        done
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ ansible_env.PATH }}"
      when: "'alta' in alta_mqm.stdout"

    - shell: if [ -f {{ gdmlcfsasb }}mqm8.asb ]; then echo alta; fi
      register: alta_mqm8

    - name: alta canales MQ8
      become: yes
      become_user: mqm
      become_method: su
      become_exe: sudo su -
      shell: |
        for i in $(cat {{ gdmlcfsasb }}mqm8.asb)
        do
        $(cat {{ gdmlcfsasb }}mqm8a.asb) $i
        done
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ ansible_env.PATH }}"
      when: "'alta' in alta_mqm8.stdout"

    - shell: if [ -f {{ gdmlcfsasb }}mqm9.asb ]; then echo alta; fi
      register: alta_mqm9

    - name: alta canales MQ9
      become: yes
      become_user: mqm
      become_method: su
      become_exe: sudo su -
      shell: |
        for i in $(cat {{ gdmlcfsasb }}mqm8.asb)
        do
        $(cat {{ gdmlcfsasb }}mqm9a.asb) $i
        done
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ ansible_env.PATH }}"
      when: "'alta' in alta_mqm9.stdout"

    - shell: if [ -f {{ gdmlcfsasb }}mqm90.asb ]; then echo alta; fi
      register: alta_mqm90

    - name: alta canales MQ90
      become: yes
      become_user: mqm
      become_method: su
      become_exe: sudo su -
      shell: |
        for i in $(cat {{ gdmlcfsasb }}mqm90.asb)
        do
        $(cat {{ gdmlcfsasb }}mqm90a.asb) $i
        done
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ ansible_env.PATH }}"
      when: "'alta' in alta_mqm90.stdout"

    - shell: if [ -f {{ gdmlcfsasb }}mqm93.asb ]; then echo alta; fi
      register: alta_mqm93

    - name: alta canales MQ93
      become: yes
      become_user: mqm
      become_method: su
      become_exe: sudo su -
      shell: |
        for i in $(cat {{ gdmlcfsasb }}mqm93.asb)
        do
        $(cat {{ gdmlcfsasb }}mqm93a.asb) $i
        done
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ ansible_env.PATH }}"
      when: "'alta' in alta_mqm93.stdout"