- block:
    - set_fact:
        nombre_servidor: "{{ idcrqincreq }}_{{ inventory_hostname.split('.')[0] }}"
        direccion_ip: "{{ hostvars[inventory_hostname].ipaddress }}"


    - name: Reporte - Hostname, IPs, Uptime posterior IPL
      debug: 
        msg: "{{ nombre_servidor }}-{{ direccion_ip }}"