- block:
    - name: Recopilar información del servidor
      set_fact:
        server_info:
          ip: "{{ ansible_default_ipv4.address }}"
          hostname: "{{ inventory_hostname }}"
          os_pre: "{{ os_pre }}"
          os_post: "{{ os_post }}"
          status: "{{ domain_status }}"

    - name: Crear línea CSV para este servidor
      set_fact:
        csv_line: "{{ server_info.ip }},{{ server_info.hostname }},{{ server_info.os_pre }},{{ server_info.os_post }},{{ server_info.status }}"

    - name: Crear diccionario para set_stats
      set_fact:
        stats_data: "{{ stats_data | default({}) | combine({inventory_hostname: csv_line}) }}"

    - name: Enviar datos a Artifacts
      set_stats:
        data: "{{ stats_data }}"
        per_host: yes