---
- name: Ejeplo Nun.1
  shell: echo "VGAPPS,OK"
  register: info1

- name: Crear echos dinamicos
  set_fact:
    valor1: "{{ info1.stdout.split(',')[1] }}"

- name: Resultado de la validacion VG VGAPPS
  assert:
    that:
      - "'OK' in valor1"
    fail_msg: 
      - "El VG VGAPPS no existe"
      - "Utilizar la plantilla de nombre bvm_jobtemplate_lvm_linux"
      - "y crear el VGAPPS"
      - "Acceder a la URL: https://ansible-tower.eu4.cacf.kyndryl.net/#/templates/job_template/133308/detail"

- name: Ejeplo Nun.2
  shell: echo "VGAPPS,KO"
  register: info2

- name: Crear echos dinamicos
  set_fact:
    valor2: "{{ info2.stdout.split(',')[1] }}"
- name: Resultado de la validacion VG VGAPPS
  assert:
    that:
      - "'OK' in valor2"
    fail_msg: 
      - "El VG VGAPPS no tiene espacion suficiente"
      - "Utilizar la plantilla de nombre bvm_jobtemplate_lvm_linux"
      - "y extender el VGAPPS"
      - "Acceda a la URL: https://ansible-tower.eu4.cacf.kyndryl.net/#/templates/job_template/133308/details"