---
- name: Tareas por bloques - Validacion formato CRQ o ICR
  block:
    - name: Validando Formato de Cambio o Incidente
      assert:
        that:
          - idcrqincreq | string | regex_search('(CRQ|INC|REQ)[0-9]{12}')
        fail_msg: "El CRQ, INC o REQ no cumplen con la condiciones del formato"
        success_msg: "El CRQ, INC o REQ cumplen con las condiciones del formato"
      run_once: true
      delegate_to: localhost

- name: Archivos de evidencias servidores
  block:
    - file:
        path: "{{ mountfsasb }}{{ item }}"
        state: directory

    - file:
        path: "{{ gdmlcfsasb }}{{ item }}"
        state: touch
        owner: bvmuxat2
        group: automate
      loop:
        - foto_salud_servidor_previa.txt
        - foto_pp_previa.txt
        - patrol.asb
        - capacity.asb
        - ctm.asb
        - dim.asb
        - cd.asb
        - s1.asb
      become: true