---
- name: Tareas por bloques - Validacion formato CRQ o ICR
  block:
    - name: Validando Formato de Cambio o Incidente
      assert:
        that:
          - idcrqincreq | string | regex_search('(CRQ|INC|REQ)[0-9]{12}')
        fail_msg: "El CRQ, INC o REQ no cumplen con la condiciones del formato"
        success_msg: "El CRQ, INC o REQ cumplen con las condiciones del formato"
      run_once: true
      delegate_to: localhost

    - name: Copiar csd_redhat_scan.txt
      become: true
      copy:
        src: files/csd_redhat_scan.txt
        dest: "{{ mountfsasb }}/csd_redhat_scan.sh"
        mode: 0750
        owner: bvmuxat2
        group: automate

    - name: Ejecutar el script csd_redhat_scan
      become: true
      shell: ./csd_redhat_scan.sh -c
      args:
        executable: /bin/ksh
        chdir: /var/opt/ansible
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ ansible_env.PATH }}"

    - name: Obtener el ultomo reporte de csd_redhat_scan
      become: true
      shell: ls -1rt | tail -1
      args:
        chdir: /var/opt/ansible/checklist
      register: ultimo_repo_csd_linux

    - name: Obtener la salida del ultomo reporte de csd_redhat_scan
      become: true
      shell: "cat {{ ultimo_repo_csd.stdout }}"
      args:
        chdir: /var/opt/ansible/checklist
      register: echo_repo_csd_linux