- block:
    - name: Obtener version OS
      shell: cat osrelease.txt
      args:
        chdir: /tmp
      register: vessionos

    - set_fact:
        nombre_servidor: "{{ inventory_hostname.split('.')[0] }}"
        direccion_ip: "{{ hostvars[inventory_hostname].ipaddress }}"
        release_os: "{{ vessionos.stdout }}"

    - set_fact:
        salida_os: |
          {% if '8' in release_os %}
          {{ nombre_servidor }},{{ direccion_ip }},CORRECTO-soportosdimeok
          {% else %}
          {{ nombre_servidor }},{{ direccion_ip }},FALLA-soportosdimeko
          {% endif %}

    - debug:
        msg: "{{ salida_os.split('-')[0] | trim }}"

# - block:
#     - lineinfile:
#         path: /tmp/concentrado1.txt
#         line: "{{ salida_os | join('\n') }}"
#         create: true
#   delegate_to: lvbtst01.bvm.bluecare.kyndryl.net

# - name: Forzar a un FALLO
#   assert:
#     that:
#       - "'8' in release_os"
#     fail_msg: "{{ nombre_servidor }},{{ direccion_ip }},FALLA"
#     success_msg: "{{ nombre_servidor }},{{ direccion_ip }},CORRECTO"

