- block:
    - name: Validando Formato de Cambio o Incidente
      assert:
        that:
          - idcrqincreq | string | regex_search('(CRQ|INC|REQ)[0-9]{12}')
        fail_msg: "El CRQ, INC o REQ no cumplen con la condiciones del formato"
        success_msg: "El CRQ, INC o REQ cumplen con las condiciones del formato"
      run_once: true
      delegate_to: localhost

- block:
    - name: Validacion de VG Java
      become: true
      shell: vgs 2>/dev/null | grep -qi VGAPPS && echo OK || echo KO
      register: vgvaljav

    - name: Resultado de la valida VG Java
      assert:
        that:
          - vgvaljav.stdout in "OK"
        fail_msg: "El VG VGAPPS no existe"

    - name: Validacion del tamaño VG Java 
      become: true
      shell: |
        vgfree=$(vgs | grep -i VGAPPS | tr -s ' ' ',' | cut -d, -f8 | tr -d '<gG' | cut -d. -f1)
        if [ $vgfree -ge 6 ]; then
        echo "OK,$vgfree"
        elif [ $vgfree -ge 5 ]; then
        echo "KO,$vgfree"
        elif [ $vgfree -ge 4 ]; then
        echo "KO,$vgfree"
        fi
      register: vgszjav
      when: vgvaljav.stdout.split(',')[0] in "OK"

    - name: Resultado de la valida VG Java
      assert:
        that:
          - vgszjav.stdout.split(',')[0] in "OK"
        fail_msg: "El VG VGAPPS no tiene espacion suficiente"

    - name: Validacion de LV Java
      become: true
      shell: lvs 2>/dev/null | grep -qi LVJAVACTM && echo OK || echo KO
      register: fsvaljav

    - name: Resultado de la valida LV Java
      assert:
        that:
          - fsvaljav.stdout in "OK"
        fail_msg: "El LV LVJAVA no existe"
      ignore_errors: true

    - name: Validacion de Java version
      become: true
      shell: |
        javapath=$(ls -1 / | grep ^java_\w*)
        javabin=$(ls -lR /$javapath | grep /bin: | tr -d ":")
        $javabin/java --version | head -1 | tr -s ' ' ',' | cut -d, -f2
      register: javer
      when: fsvaljav.stdout in "OK"

    - name: Resultado de la Validacion de la version de Java
      debug:
        msg: "La version actual de java en el equipo es {{ fsvaljav.stdout }}"
      when: fsvaljav.stdout in "OK"

    - name: Incluir role de remediacion VG, LV y Dir Java
      include_tasks: remediar/crear_lv.yml
      when: fsvaljav.stdout in "KO"

    - name: Incluir role de remediacion VG, LV y Dir Java
      include_tasks: remediar/extender_lv.yml
      when: fsvaljav.stdout in "KO"
